// GENERATED BY COPILOT (manual adapter; no build_runner required)
// ignore_for_file: type=lint

part of 'local_user.dart';

class LocalUserAdapter extends TypeAdapter<LocalUser> {
  @override
  final int typeId = 1;

  @override
  LocalUser read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (var i = 0; i < numOfFields; i++) {
      final fieldNum = reader.readByte();
      fields[fieldNum] = reader.read();
    }

    return LocalUser(
      email: fields[0] as String,
      fullName: fields[1] as String,
      phone: fields[2] as String,
      roleIndex: fields[3] as int,
      passwordHash: fields[4] as String,
      dob: fields[5] as String?,
      citizenshipNumber: fields[6] as String?,
      district: fields[7] as String?,
      municipality: fields[8] as String?,
      ward: fields[9] as String?,
      tole: fields[10] as String?,
      createdAt: fields[11] as DateTime,
    );
  }

  @override
  void write(BinaryWriter writer, LocalUser obj) {
    writer
      ..writeByte(12)
      ..writeByte(0)
      ..write(obj.email)
      ..writeByte(1)
      ..write(obj.fullName)
      ..writeByte(2)
      ..write(obj.phone)
      ..writeByte(3)
      ..write(obj.roleIndex)
      ..writeByte(4)
      ..write(obj.passwordHash)
      ..writeByte(5)
      ..write(obj.dob)
      ..writeByte(6)
      ..write(obj.citizenshipNumber)
      ..writeByte(7)
      ..write(obj.district)
      ..writeByte(8)
      ..write(obj.municipality)
      ..writeByte(9)
      ..write(obj.ward)
      ..writeByte(10)
      ..write(obj.tole)
      ..writeByte(11)
      ..write(obj.createdAt);
  }
}
